[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@everest/contracts=lib/everest-chainlink-consumer/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@openzeppelin/contracts=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts",
]

[invariant]
runs = 64
depth = 32
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
